### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by cohenshimi** [MISP/misp-sighting-server#3]
hey ,

I tried to install the module on the same MISP server ubuntu 16.04 . Not sure it matters but instead of "git submodule update" I used "git clone https://github.com/yinqiwen/ardb.git" because of the SSH I can't open. When I finish installing, I try Starting the ReST API server and encounter the "configparser.NoSectionError: No section: 'server'" error.
I changed the file name from server.cfg.sample to server.cfg and did not change the settings inside (need to change them?). Now I'm having the error "redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /tmp/ardb.sock. No such file or directory."
The file really does not exist, should it be created manually? So what settings should I put in it? 

Thank you !
Shimi

**Comment by adulau** [comment]
The latest update to kvrocks should fix the issue. The configuration file is indeed a sample file that you need to copy.
