### ISSUE TITLE
Connection from MISP Error 403

### ISSUE THREAD

**Issue by ch4r13** [MISP/misp-sighting-server#6]
Hi, I would like to ask if I understood this "misp-sighting-server" correctly. I thought that it serves as a database to store "sightings" for individual attributes for multiple MISP instances. But I have a problem with the connection from MISP. The instance is communicating correctly, I tried listening via netcat and MISP is communicating. I get the error message **Error 403:**, but my "misp-sighting-server" via "curl" responds correctly. ( `curl --header 'X-API-Key: afdef83f9cc7c87b801c36e4af632ef06af2f2ef' -X PUT  http://127.0.0.1:5000/add -d "value=127.0.0.1&type=0&org_uuid=0acdaad8-b305-482f-a904-78330640636b"  -d "source=honeypot"`)

![image](https://user-images.githubusercontent.com/32222739/221118919-bb1ac912-d526-42ed-9dd1-23c844788505.png)

**Comment by adulau** [comment]
You are right. The misp-sighting server is different than the https://github.com/stricaud/sightingdb. Currently the code in MISP is for the SightingDB  but we will extend soon to support misp-sighting-server.

**Comment by ch4r13** [comment]
Okay, thanks for your reply.

**Comment by thezolin** [comment]
Hello, 

I'm using 2.4.177 version of MISP, and still receive same error message discussed on this topic. 
Does anyone knows if this connection between MISP and misp-sighting-server is available already for this version? 

Thanks in advance.

**Comment by tiagosequeira** [comment]
> You are right. The misp-sighting server is different than the https://github.com/stricaud/sightingdb. Currently the code in MISP is for the SightingDB  but we will extend soon to support misp-sighting-server.

Hello. Any news regarding this important feature? Thanks in advance.
